// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (code, name, type, parent_id, level, is_system, is_control, is_active, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, code, name, type, parent_id, level, is_system, is_control, is_active, created_by, created_at, updated_at
`

type CreateAccountParams struct {
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	Type      AccountType `json:"type"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Level     int32       `json:"level"`
	IsSystem  bool        `json:"is_system"`
	IsControl bool        `json:"is_control"`
	IsActive  bool        `json:"is_active"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.ParentID,
		arg.Level,
		arg.IsSystem,
		arg.IsControl,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Level,
		&i.IsSystem,
		&i.IsControl,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, code, name, type, parent_id, level, is_system, is_control, is_active, created_by, created_at, updated_at
FROM accounts
WHERE code = $1
`

func (q *Queries) GetAccountByCode(ctx context.Context, code string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, code)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Level,
		&i.IsSystem,
		&i.IsControl,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, code, name, type, parent_id, level, is_system, is_control, is_active, created_by, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Level,
		&i.IsSystem,
		&i.IsControl,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountChildren = `-- name: GetAccountChildren :many
SELECT id, code, name, type, parent_id, level, is_system, is_control, is_active, created_by, created_at, updated_at
FROM accounts
WHERE parent_id = $1 AND is_active = true
ORDER BY code ASC
`

func (q *Queries) GetAccountChildren(ctx context.Context, parentID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Level,
			&i.IsSystem,
			&i.IsControl,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountIDByCode = `-- name: GetAccountIDByCode :one
SELECT id FROM accounts WHERE code = $1 LIMIT 1
`

func (q *Queries) GetAccountIDByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAccountIDByCode, code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllAccounts = `-- name: GetAllAccounts :many

SELECT id, code, name, type, parent_id, level, is_system, is_control, is_active, created_by, created_at, updated_at
FROM accounts
WHERE is_active = true
ORDER BY code ASC
`

// ============================================================================
// ACCOUNTS (Chart of Accounts)
// ============================================================================
func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Level,
			&i.IsSystem,
			&i.IsControl,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAccountsWithBalances = `-- name: GetAllAccountsWithBalances :many
SELECT
    a.id, a.code, a.name, a.type, a.parent_id, a.level,
    a.is_system, a.is_control, a.is_active, a.created_by,
    a.created_at, a.updated_at,
    COALESCE(
        CASE
            WHEN a.type IN ('asset', 'expense')
                THEN SUM(COALESCE(jel.debit, 0)) - SUM(COALESCE(jel.credit, 0))
            ELSE
                SUM(COALESCE(jel.credit, 0)) - SUM(COALESCE(jel.debit, 0))
        END,
    0)::NUMERIC(18,2) AS balance
FROM accounts a
LEFT JOIN journal_entry_lines jel ON jel.account_id = a.id
LEFT JOIN journal_entries je ON je.id = jel.journal_entry_id AND je.status = 'posted'
WHERE a.is_active = true
GROUP BY a.id, a.code, a.name, a.type, a.parent_id, a.level,
    a.is_system, a.is_control, a.is_active, a.created_by,
    a.created_at, a.updated_at
ORDER BY a.code ASC
`

type GetAllAccountsWithBalancesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Type      AccountType        `json:"type"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Level     int32              `json:"level"`
	IsSystem  bool               `json:"is_system"`
	IsControl bool               `json:"is_control"`
	IsActive  bool               `json:"is_active"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Balance   pgtype.Numeric     `json:"balance"`
}

func (q *Queries) GetAllAccountsWithBalances(ctx context.Context) ([]GetAllAccountsWithBalancesRow, error) {
	rows, err := q.db.Query(ctx, getAllAccountsWithBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAccountsWithBalancesRow
	for rows.Next() {
		var i GetAllAccountsWithBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Level,
			&i.IsSystem,
			&i.IsControl,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasAccountChildren = `-- name: HasAccountChildren :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE parent_id = $1 AND is_active = true) AS has_children
`

func (q *Queries) HasAccountChildren(ctx context.Context, parentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasAccountChildren, parentID)
	var has_children bool
	err := row.Scan(&has_children)
	return has_children, err
}

const isAccountReferencedInJournalLines = `-- name: IsAccountReferencedInJournalLines :one
SELECT EXISTS(SELECT 1 FROM journal_entry_lines WHERE account_id = $1) AS is_referenced
`

func (q *Queries) IsAccountReferencedInJournalLines(ctx context.Context, accountID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountReferencedInJournalLines, accountID)
	var is_referenced bool
	err := row.Scan(&is_referenced)
	return is_referenced, err
}

const searchAccounts = `-- name: SearchAccounts :many
SELECT id, code, name, type, parent_id, level, is_system, is_control, is_active, created_by, created_at, updated_at
FROM accounts
WHERE is_active = true
  AND (
    $1::TEXT IS NULL
    OR code ILIKE '%' || $1::TEXT || '%'
    OR name ILIKE '%' || $1::TEXT || '%'
  )
  AND (
    $2::account_type IS NULL
    OR type = $2::account_type
  )
  AND (
    $3::UUID IS NULL
    OR parent_id = $3::UUID
  )
ORDER BY code ASC
`

type SearchAccountsParams struct {
	Search      pgtype.Text     `json:"search"`
	AccountType NullAccountType `json:"account_type"`
	ParentID    pgtype.UUID     `json:"parent_id"`
}

func (q *Queries) SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccounts, arg.Search, arg.AccountType, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ParentID,
			&i.Level,
			&i.IsSystem,
			&i.IsControl,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET code = $2, name = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, code, name, type, parent_id, level, is_system, is_control, is_active, created_by, created_at, updated_at
`

type UpdateAccountParams struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Code, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.ParentID,
		&i.Level,
		&i.IsSystem,
		&i.IsControl,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
