// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM customers
WHERE ($1::BOOLEAN IS NULL OR is_active = $1::BOOLEAN)
  AND ($2::TEXT IS NULL OR name ILIKE '%' || $2::TEXT || '%')
`

type CountCustomersParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.IsActive, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, email, phone, address, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, address, is_active,
          created_by, created_at, updated_at
`

type CreateCustomerParams struct {
	Name      string      `json:"name"`
	Email     pgtype.Text `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Address   pgtype.Text `json:"address"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.CreatedBy,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const getCustomerByID = `-- name: GetCustomerByID :one

SELECT id, name, email, phone, address, is_active,
       created_by, created_at, updated_at
FROM customers
WHERE id = $1
`

// ============================================================================
// CUSTOMERS
// ============================================================================
func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, email, phone, address, is_active,
       created_by, created_at, updated_at
FROM customers
WHERE ($3::BOOLEAN IS NULL OR is_active = $3::BOOLEAN)
  AND ($4::TEXT IS NULL OR name ILIKE '%' || $4::TEXT || '%')
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	IsActive pgtype.Bool `json:"is_active"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.Limit,
		arg.Offset,
		arg.IsActive,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerActive = `-- name: SetCustomerActive :one
UPDATE customers
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone, address, is_active,
          created_by, created_at, updated_at
`

type SetCustomerActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetCustomerActive(ctx context.Context, arg SetCustomerActiveParams) (Customer, error) {
	row := q.db.QueryRow(ctx, setCustomerActive, arg.ID, arg.IsActive)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $2, email = $3, phone = $4, address = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone, address, is_active,
          created_by, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Email   pgtype.Text `json:"email"`
	Phone   pgtype.Text `json:"phone"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Address,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
