// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
WHERE ($1::UUID IS NULL OR customer_id = $1::UUID)
  AND ($2::invoice_status IS NULL OR status = $2::invoice_status)
`

type CountInvoicesParams struct {
	CustomerID pgtype.UUID       `json:"customer_id"`
	Status     NullInvoiceStatus `json:"status"`
}

func (q *Queries) CountInvoices(ctx context.Context, arg CountInvoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices, arg.CustomerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvoicesAging = `-- name: CountInvoicesAging :one
SELECT COUNT(*) FROM invoices
WHERE status IN ('unpaid', 'partially_paid')
`

func (q *Queries) CountInvoicesAging(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoicesAging)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (invoice_number, customer_id, issue_date, due_date, total_amount, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, invoice_number, customer_id, issue_date, due_date,
          total_amount, amount_paid, status, description,
          created_by, created_at, updated_at
`

type CreateInvoiceParams struct {
	InvoiceNumber string         `json:"invoice_number"`
	CustomerID    pgtype.UUID    `json:"customer_id"`
	IssueDate     pgtype.Date    `json:"issue_date"`
	DueDate       pgtype.Date    `json:"due_date"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
	Description   pgtype.Text    `json:"description"`
	CreatedBy     pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.CustomerID,
		arg.IssueDate,
		arg.DueDate,
		arg.TotalAmount,
		arg.Description,
		arg.CreatedBy,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerID,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.Status,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1 AND status = 'unpaid'
`

func (q *Queries) DeleteInvoice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const generateInvoiceNumber = `-- name: GenerateInvoiceNumber :one
SELECT 'INV-' || to_char(CURRENT_DATE, 'YYYY') || '-' ||
       LPAD((COALESCE(
           (SELECT COUNT(*) + 1 FROM invoices
            WHERE invoice_number LIKE 'INV-' || to_char(CURRENT_DATE, 'YYYY') || '-%'),
           1
       ))::TEXT, 3, '0') AS invoice_number
`

func (q *Queries) GenerateInvoiceNumber(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, generateInvoiceNumber)
	var invoice_number interface{}
	err := row.Scan(&invoice_number)
	return invoice_number, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one

SELECT id, invoice_number, customer_id, issue_date, due_date,
       total_amount, amount_paid, status, description,
       created_by, created_at, updated_at
FROM invoices
WHERE id = $1
`

// ============================================================================
// INVOICES (Penagihan / AR)
// ============================================================================
func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerID,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.Status,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, invoice_number, customer_id, issue_date, due_date,
       total_amount, amount_paid, status, description,
       created_by, created_at, updated_at
FROM invoices
WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerID,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.Status,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceivablesSummary = `-- name: GetReceivablesSummary :one
SELECT
    COALESCE(SUM(total_amount - amount_paid), 0)::NUMERIC(18,2) AS total_outstanding,
    COALESCE(SUM(CASE WHEN due_date < CURRENT_DATE THEN total_amount - amount_paid ELSE 0 END), 0)::NUMERIC(18,2) AS total_overdue
FROM invoices
WHERE status IN ('unpaid', 'partially_paid')
`

type GetReceivablesSummaryRow struct {
	TotalOutstanding pgtype.Numeric `json:"total_outstanding"`
	TotalOverdue     pgtype.Numeric `json:"total_overdue"`
}

func (q *Queries) GetReceivablesSummary(ctx context.Context) (GetReceivablesSummaryRow, error) {
	row := q.db.QueryRow(ctx, getReceivablesSummary)
	var i GetReceivablesSummaryRow
	err := row.Scan(&i.TotalOutstanding, &i.TotalOverdue)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.invoice_number, i.customer_id, i.issue_date, i.due_date,
       i.total_amount, i.amount_paid, i.status, i.description,
       i.created_by, i.created_at, i.updated_at,
       c.name AS customer_name
FROM invoices i
JOIN customers c ON c.id = i.customer_id
WHERE ($3::UUID IS NULL OR i.customer_id = $3::UUID)
  AND ($4::invoice_status IS NULL OR i.status = $4::invoice_status)
ORDER BY i.due_date ASC
LIMIT $1 OFFSET $2
`

type ListInvoicesParams struct {
	Limit      int32             `json:"limit"`
	Offset     int32             `json:"offset"`
	CustomerID pgtype.UUID       `json:"customer_id"`
	Status     NullInvoiceStatus `json:"status"`
}

type ListInvoicesRow struct {
	ID            pgtype.UUID        `json:"id"`
	InvoiceNumber string             `json:"invoice_number"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	IssueDate     pgtype.Date        `json:"issue_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	Status        InvoiceStatus      `json:"status"`
	Description   pgtype.Text        `json:"description"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CustomerName  string             `json:"customer_name"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.Limit,
		arg.Offset,
		arg.CustomerID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerID,
			&i.IssueDate,
			&i.DueDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.Status,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesAging = `-- name: ListInvoicesAging :many
SELECT i.id, i.invoice_number, i.customer_id, i.issue_date, i.due_date,
       i.total_amount, i.amount_paid, i.status, i.description,
       i.created_by, i.created_at, i.updated_at,
       c.name AS customer_name,
       (CURRENT_DATE - i.due_date) AS days_overdue
FROM invoices i
JOIN customers c ON c.id = i.customer_id
WHERE i.status IN ('unpaid', 'partially_paid')
ORDER BY i.due_date ASC
LIMIT $1 OFFSET $2
`

type ListInvoicesAgingParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListInvoicesAgingRow struct {
	ID            pgtype.UUID        `json:"id"`
	InvoiceNumber string             `json:"invoice_number"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	IssueDate     pgtype.Date        `json:"issue_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	Status        InvoiceStatus      `json:"status"`
	Description   pgtype.Text        `json:"description"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CustomerName  string             `json:"customer_name"`
	DaysOverdue   int32              `json:"days_overdue"`
}

func (q *Queries) ListInvoicesAging(ctx context.Context, arg ListInvoicesAgingParams) ([]ListInvoicesAgingRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesAging, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesAgingRow
	for rows.Next() {
		var i ListInvoicesAgingRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerID,
			&i.IssueDate,
			&i.DueDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.Status,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.DaysOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpaidInvoicesByCustomer = `-- name: ListUnpaidInvoicesByCustomer :many
SELECT id, invoice_number, customer_id, issue_date, due_date,
       total_amount, amount_paid, status, description,
       created_by, created_at, updated_at
FROM invoices
WHERE customer_id = $1
  AND status IN ('unpaid', 'partially_paid')
ORDER BY due_date ASC
`

func (q *Queries) ListUnpaidInvoicesByCustomer(ctx context.Context, customerID pgtype.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listUnpaidInvoicesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CustomerID,
			&i.IssueDate,
			&i.DueDate,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.Status,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices
SET invoice_number = $2, issue_date = $3, due_date = $4,
    total_amount = $5, description = $6, updated_at = NOW()
WHERE id = $1 AND status = 'unpaid'
RETURNING id, invoice_number, customer_id, issue_date, due_date,
          total_amount, amount_paid, status, description,
          created_by, created_at, updated_at
`

type UpdateInvoiceParams struct {
	ID            pgtype.UUID    `json:"id"`
	InvoiceNumber string         `json:"invoice_number"`
	IssueDate     pgtype.Date    `json:"issue_date"`
	DueDate       pgtype.Date    `json:"due_date"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
	Description   pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoice,
		arg.ID,
		arg.InvoiceNumber,
		arg.IssueDate,
		arg.DueDate,
		arg.TotalAmount,
		arg.Description,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CustomerID,
		&i.IssueDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.Status,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceAmountPaid = `-- name: UpdateInvoiceAmountPaid :exec
UPDATE invoices
SET amount_paid = amount_paid + $1::NUMERIC(18,2),
    status = CASE
        WHEN amount_paid + $1::NUMERIC(18,2) >= total_amount THEN 'paid'::invoice_status
        ELSE 'partially_paid'::invoice_status
    END,
    updated_at = NOW()
WHERE id = $2
`

type UpdateInvoiceAmountPaidParams struct {
	Addition pgtype.Numeric `json:"addition"`
	ID       pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateInvoiceAmountPaid(ctx context.Context, arg UpdateInvoiceAmountPaidParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceAmountPaid, arg.Addition, arg.ID)
	return err
}
