// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_entry_lines.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalEntryLine = `-- name: CreateJournalEntryLine :one
INSERT INTO journal_entry_lines (journal_entry_id, account_id, debit, credit, line_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, journal_entry_id, account_id, debit, credit, line_order, created_at
`

type CreateJournalEntryLineParams struct {
	JournalEntryID pgtype.UUID    `json:"journal_entry_id"`
	AccountID      pgtype.UUID    `json:"account_id"`
	Debit          pgtype.Numeric `json:"debit"`
	Credit         pgtype.Numeric `json:"credit"`
	LineOrder      int32          `json:"line_order"`
}

func (q *Queries) CreateJournalEntryLine(ctx context.Context, arg CreateJournalEntryLineParams) (JournalEntryLine, error) {
	row := q.db.QueryRow(ctx, createJournalEntryLine,
		arg.JournalEntryID,
		arg.AccountID,
		arg.Debit,
		arg.Credit,
		arg.LineOrder,
	)
	var i JournalEntryLine
	err := row.Scan(
		&i.ID,
		&i.JournalEntryID,
		&i.AccountID,
		&i.Debit,
		&i.Credit,
		&i.LineOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJournalEntryLinesByEntryID = `-- name: DeleteJournalEntryLinesByEntryID :exec
DELETE FROM journal_entry_lines WHERE journal_entry_id = $1
`

func (q *Queries) DeleteJournalEntryLinesByEntryID(ctx context.Context, journalEntryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJournalEntryLinesByEntryID, journalEntryID)
	return err
}

const getAccountLedger = `-- name: GetAccountLedger :many
SELECT jel.id, jel.journal_entry_id, jel.account_id,
       jel.debit, jel.credit, jel.line_order, jel.created_at,
       je.entry_number, je.date AS entry_date, je.status AS entry_status
FROM journal_entry_lines jel
JOIN journal_entries je ON je.id = jel.journal_entry_id
WHERE jel.account_id = $1
  AND je.status = 'posted'
  AND ($2::DATE IS NULL OR je.date >= $2::DATE)
  AND ($3::DATE IS NULL OR je.date <= $3::DATE)
ORDER BY je.date ASC, jel.line_order ASC
`

type GetAccountLedgerParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetAccountLedgerRow struct {
	ID             pgtype.UUID        `json:"id"`
	JournalEntryID pgtype.UUID        `json:"journal_entry_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	Debit          pgtype.Numeric     `json:"debit"`
	Credit         pgtype.Numeric     `json:"credit"`
	LineOrder      int32              `json:"line_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EntryNumber    string             `json:"entry_number"`
	EntryDate      pgtype.Date        `json:"entry_date"`
	EntryStatus    JournalStatus      `json:"entry_status"`
}

func (q *Queries) GetAccountLedger(ctx context.Context, arg GetAccountLedgerParams) ([]GetAccountLedgerRow, error) {
	rows, err := q.db.Query(ctx, getAccountLedger, arg.AccountID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountLedgerRow
	for rows.Next() {
		var i GetAccountLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
			&i.LineOrder,
			&i.CreatedAt,
			&i.EntryNumber,
			&i.EntryDate,
			&i.EntryStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalEntryLinesByEntryID = `-- name: GetJournalEntryLinesByEntryID :many

SELECT jel.id, jel.journal_entry_id, jel.account_id,
       jel.debit, jel.credit, jel.line_order, jel.created_at,
       a.code AS account_code, a.name AS account_name
FROM journal_entry_lines jel
JOIN accounts a ON a.id = jel.account_id
WHERE jel.journal_entry_id = $1
ORDER BY jel.line_order ASC
`

type GetJournalEntryLinesByEntryIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	JournalEntryID pgtype.UUID        `json:"journal_entry_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	Debit          pgtype.Numeric     `json:"debit"`
	Credit         pgtype.Numeric     `json:"credit"`
	LineOrder      int32              `json:"line_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AccountCode    string             `json:"account_code"`
	AccountName    string             `json:"account_name"`
}

// ============================================================================
// JOURNAL ENTRY LINES (Detail Jurnal)
// ============================================================================
func (q *Queries) GetJournalEntryLinesByEntryID(ctx context.Context, journalEntryID pgtype.UUID) ([]GetJournalEntryLinesByEntryIDRow, error) {
	rows, err := q.db.Query(ctx, getJournalEntryLinesByEntryID, journalEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJournalEntryLinesByEntryIDRow
	for rows.Next() {
		var i GetJournalEntryLinesByEntryIDRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
			&i.LineOrder,
			&i.CreatedAt,
			&i.AccountCode,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalEntryLinesTotals = `-- name: GetJournalEntryLinesTotals :one
SELECT COALESCE(SUM(debit), 0)::NUMERIC(18,2) AS total_debit,
       COALESCE(SUM(credit), 0)::NUMERIC(18,2) AS total_credit
FROM journal_entry_lines
WHERE journal_entry_id = $1
`

type GetJournalEntryLinesTotalsRow struct {
	TotalDebit  pgtype.Numeric `json:"total_debit"`
	TotalCredit pgtype.Numeric `json:"total_credit"`
}

func (q *Queries) GetJournalEntryLinesTotals(ctx context.Context, journalEntryID pgtype.UUID) (GetJournalEntryLinesTotalsRow, error) {
	row := q.db.QueryRow(ctx, getJournalEntryLinesTotals, journalEntryID)
	var i GetJournalEntryLinesTotalsRow
	err := row.Scan(&i.TotalDebit, &i.TotalCredit)
	return i, err
}
