// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_entries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJournalEntries = `-- name: CountJournalEntries :one
SELECT COUNT(*) FROM journal_entries
WHERE ($1::journal_status IS NULL OR status = $1::journal_status)
  AND ($2::TEXT IS NULL OR source = $2::TEXT)
  AND ($3::DATE IS NULL OR date >= $3::DATE)
  AND ($4::DATE IS NULL OR date <= $4::DATE)
`

type CountJournalEntriesParams struct {
	Status    NullJournalStatus `json:"status"`
	Source    pgtype.Text       `json:"source"`
	StartDate pgtype.Date       `json:"start_date"`
	EndDate   pgtype.Date       `json:"end_date"`
}

func (q *Queries) CountJournalEntries(ctx context.Context, arg CountJournalEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalEntries,
		arg.Status,
		arg.Source,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (entry_number, date, description, source, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entry_number, date, description, status,
          total_debit, total_credit, reversal_of, reversal_reason,
          reversed_by, source, created_by, created_at, updated_at
`

type CreateJournalEntryParams struct {
	EntryNumber string        `json:"entry_number"`
	Date        pgtype.Date   `json:"date"`
	Description string        `json:"description"`
	Source      pgtype.Text   `json:"source"`
	Status      JournalStatus `json:"status"`
	CreatedBy   pgtype.UUID   `json:"created_by"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.EntryNumber,
		arg.Date,
		arg.Description,
		arg.Source,
		arg.Status,
		arg.CreatedBy,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryNumber,
		&i.Date,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.ReversalOf,
		&i.ReversalReason,
		&i.ReversedBy,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReversalJournalEntry = `-- name: CreateReversalJournalEntry :one
INSERT INTO journal_entries (entry_number, date, description, source, status, reversal_of, reversal_reason, created_by)
VALUES ($1, $2, $3, $4, 'posted', $5, $6, $7)
RETURNING id, entry_number, date, description, status,
          total_debit, total_credit, reversal_of, reversal_reason,
          reversed_by, source, created_by, created_at, updated_at
`

type CreateReversalJournalEntryParams struct {
	EntryNumber    string      `json:"entry_number"`
	Date           pgtype.Date `json:"date"`
	Description    string      `json:"description"`
	Source         pgtype.Text `json:"source"`
	ReversalOf     pgtype.UUID `json:"reversal_of"`
	ReversalReason pgtype.Text `json:"reversal_reason"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateReversalJournalEntry(ctx context.Context, arg CreateReversalJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createReversalJournalEntry,
		arg.EntryNumber,
		arg.Date,
		arg.Description,
		arg.Source,
		arg.ReversalOf,
		arg.ReversalReason,
		arg.CreatedBy,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryNumber,
		&i.Date,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.ReversalOf,
		&i.ReversalReason,
		&i.ReversedBy,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJournalEntry = `-- name: DeleteJournalEntry :exec
DELETE FROM journal_entries WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteJournalEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJournalEntry, id)
	return err
}

const generateJournalEntryNumber = `-- name: GenerateJournalEntryNumber :one
SELECT 'JU-' || to_char(CURRENT_DATE, 'YYYY') || '-' ||
       LPAD((COALESCE(
           (SELECT COUNT(*) + 1 FROM journal_entries
            WHERE entry_number LIKE 'JU-' || to_char(CURRENT_DATE, 'YYYY') || '-%'),
           1
       ))::TEXT, 3, '0') AS entry_number
`

func (q *Queries) GenerateJournalEntryNumber(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, generateJournalEntryNumber)
	var entry_number interface{}
	err := row.Scan(&entry_number)
	return entry_number, err
}

const getJournalEntryByEntryNumber = `-- name: GetJournalEntryByEntryNumber :one
SELECT id, entry_number, date, description, status,
       total_debit, total_credit, reversal_of, reversal_reason,
       reversed_by, source, created_by, created_at, updated_at
FROM journal_entries
WHERE entry_number = $1
`

func (q *Queries) GetJournalEntryByEntryNumber(ctx context.Context, entryNumber string) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByEntryNumber, entryNumber)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryNumber,
		&i.Date,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.ReversalOf,
		&i.ReversalReason,
		&i.ReversedBy,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalEntryByID = `-- name: GetJournalEntryByID :one

SELECT id, entry_number, date, description, status,
       total_debit, total_credit, reversal_of, reversal_reason,
       reversed_by, source, created_by, created_at, updated_at
FROM journal_entries
WHERE id = $1
`

// ============================================================================
// JOURNAL ENTRIES (Jurnal Umum) - Headers
// ============================================================================
func (q *Queries) GetJournalEntryByID(ctx context.Context, id pgtype.UUID) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByID, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryNumber,
		&i.Date,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.ReversalOf,
		&i.ReversalReason,
		&i.ReversedBy,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, entry_number, date, description, status,
       total_debit, total_credit, reversal_of, reversal_reason,
       reversed_by, source, created_by, created_at, updated_at
FROM journal_entries
WHERE ($3::journal_status IS NULL OR status = $3::journal_status)
  AND ($4::TEXT IS NULL OR source = $4::TEXT)
  AND ($5::DATE IS NULL OR date >= $5::DATE)
  AND ($6::DATE IS NULL OR date <= $6::DATE)
ORDER BY date DESC, entry_number DESC
LIMIT $1 OFFSET $2
`

type ListJournalEntriesParams struct {
	Limit     int32             `json:"limit"`
	Offset    int32             `json:"offset"`
	Status    NullJournalStatus `json:"status"`
	Source    pgtype.Text       `json:"source"`
	StartDate pgtype.Date       `json:"start_date"`
	EndDate   pgtype.Date       `json:"end_date"`
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntries,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Source,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.EntryNumber,
			&i.Date,
			&i.Description,
			&i.Status,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.ReversalOf,
			&i.ReversalReason,
			&i.ReversedBy,
			&i.Source,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postJournalEntry = `-- name: PostJournalEntry :one
UPDATE journal_entries
SET status = 'posted',
    total_debit = $2,
    total_credit = $3,
    updated_at = NOW()
WHERE id = $1 AND status = 'draft'
RETURNING id, entry_number, date, description, status,
          total_debit, total_credit, reversal_of, reversal_reason,
          reversed_by, source, created_by, created_at, updated_at
`

type PostJournalEntryParams struct {
	ID          pgtype.UUID    `json:"id"`
	TotalDebit  pgtype.Numeric `json:"total_debit"`
	TotalCredit pgtype.Numeric `json:"total_credit"`
}

func (q *Queries) PostJournalEntry(ctx context.Context, arg PostJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, postJournalEntry, arg.ID, arg.TotalDebit, arg.TotalCredit)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryNumber,
		&i.Date,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.ReversalOf,
		&i.ReversalReason,
		&i.ReversedBy,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reverseJournalEntry = `-- name: ReverseJournalEntry :one
UPDATE journal_entries
SET status = 'reversed',
    reversed_by = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'posted'
RETURNING id, entry_number, date, description, status,
          total_debit, total_credit, reversal_of, reversal_reason,
          reversed_by, source, created_by, created_at, updated_at
`

type ReverseJournalEntryParams struct {
	ID         pgtype.UUID `json:"id"`
	ReversedBy pgtype.UUID `json:"reversed_by"`
}

func (q *Queries) ReverseJournalEntry(ctx context.Context, arg ReverseJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, reverseJournalEntry, arg.ID, arg.ReversedBy)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryNumber,
		&i.Date,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.ReversalOf,
		&i.ReversalReason,
		&i.ReversedBy,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJournalEntry = `-- name: UpdateJournalEntry :one
UPDATE journal_entries
SET description = $2, date = $3, updated_at = NOW()
WHERE id = $1 AND status = 'draft'
RETURNING id, entry_number, date, description, status,
          total_debit, total_credit, reversal_of, reversal_reason,
          reversed_by, source, created_by, created_at, updated_at
`

type UpdateJournalEntryParams struct {
	ID          pgtype.UUID `json:"id"`
	Description string      `json:"description"`
	Date        pgtype.Date `json:"date"`
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, updateJournalEntry, arg.ID, arg.Description, arg.Date)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryNumber,
		&i.Date,
		&i.Description,
		&i.Status,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.ReversalOf,
		&i.ReversalReason,
		&i.ReversedBy,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
