// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeLiability AccountType = "liability"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeRevenue   AccountType = "revenue"
	AccountTypeExpense   AccountType = "expense"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type InvoiceStatus string

const (
	InvoiceStatusUnpaid        InvoiceStatus = "unpaid"
	InvoiceStatusPartiallyPaid InvoiceStatus = "partially_paid"
	InvoiceStatusPaid          InvoiceStatus = "paid"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type JournalStatus string

const (
	JournalStatusDraft    JournalStatus = "draft"
	JournalStatusPosted   JournalStatus = "posted"
	JournalStatusReversed JournalStatus = "reversed"
)

func (e *JournalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JournalStatus(s)
	case string:
		*e = JournalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JournalStatus: %T", src)
	}
	return nil
}

type NullJournalStatus struct {
	JournalStatus JournalStatus `json:"journal_status"`
	Valid         bool          `json:"valid"` // Valid is true if JournalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJournalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JournalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JournalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJournalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JournalStatus), nil
}

type Account struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Type      AccountType        `json:"type"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Level     int32              `json:"level"`
	IsSystem  bool               `json:"is_system"`
	IsControl bool               `json:"is_control"`
	IsActive  bool               `json:"is_active"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Address   pgtype.Text        `json:"address"`
	IsActive  bool               `json:"is_active"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID            pgtype.UUID        `json:"id"`
	InvoiceNumber string             `json:"invoice_number"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	IssueDate     pgtype.Date        `json:"issue_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	Status        InvoiceStatus      `json:"status"`
	Description   pgtype.Text        `json:"description"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type JournalEntry struct {
	ID             pgtype.UUID        `json:"id"`
	EntryNumber    string             `json:"entry_number"`
	InvoiceNumber  pgtype.Text        `json:"invoice_number"`
	Date           pgtype.Date        `json:"date"`
	Description    string             `json:"description"`
	Status         JournalStatus      `json:"status"`
	TotalDebit     pgtype.Numeric     `json:"total_debit"`
	TotalCredit    pgtype.Numeric     `json:"total_credit"`
	ReversalOf     pgtype.UUID        `json:"reversal_of"`
	ReversalReason pgtype.Text        `json:"reversal_reason"`
	ReversedBy     pgtype.UUID        `json:"reversed_by"`
	Source         pgtype.Text        `json:"source"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type JournalEntryLine struct {
	ID             pgtype.UUID        `json:"id"`
	JournalEntryID pgtype.UUID        `json:"journal_entry_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	Debit          pgtype.Numeric     `json:"debit"`
	Credit         pgtype.Numeric     `json:"credit"`
	LineOrder      int32              `json:"line_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                 pgtype.UUID        `json:"id"`
	PaymentNumber      string             `json:"payment_number"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	PaymentDate        pgtype.Date        `json:"payment_date"`
	Amount             pgtype.Numeric     `json:"amount"`
	DepositToAccountID pgtype.UUID        `json:"deposit_to_account_id"`
	JournalEntryID     pgtype.UUID        `json:"journal_entry_id"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PaymentAllocation struct {
	ID        pgtype.UUID        `json:"id"`
	PaymentID pgtype.UUID        `json:"payment_id"`
	InvoiceID pgtype.UUID        `json:"invoice_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	Roles        []string           `json:"roles"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
