// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) FROM payments
WHERE ($1::UUID IS NULL OR customer_id = $1::UUID)
`

func (q *Queries) CountPayments(ctx context.Context, customerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (payment_number, customer_id, payment_date, amount, deposit_to_account_id, journal_entry_id, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, payment_number, customer_id, payment_date, amount,
          deposit_to_account_id, journal_entry_id, notes,
          created_by, created_at, updated_at
`

type CreatePaymentParams struct {
	PaymentNumber      string         `json:"payment_number"`
	CustomerID         pgtype.UUID    `json:"customer_id"`
	PaymentDate        pgtype.Date    `json:"payment_date"`
	Amount             pgtype.Numeric `json:"amount"`
	DepositToAccountID pgtype.UUID    `json:"deposit_to_account_id"`
	JournalEntryID     pgtype.UUID    `json:"journal_entry_id"`
	Notes              pgtype.Text    `json:"notes"`
	CreatedBy          pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.PaymentNumber,
		arg.CustomerID,
		arg.PaymentDate,
		arg.Amount,
		arg.DepositToAccountID,
		arg.JournalEntryID,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.CustomerID,
		&i.PaymentDate,
		&i.Amount,
		&i.DepositToAccountID,
		&i.JournalEntryID,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const generatePaymentNumber = `-- name: GeneratePaymentNumber :one
SELECT 'PAY-' || to_char(CURRENT_DATE, 'YYYY') || '-' ||
       LPAD((COALESCE(
           (SELECT COUNT(*) + 1 FROM payments
            WHERE payment_number LIKE 'PAY-' || to_char(CURRENT_DATE, 'YYYY') || '-%'),
           1
       ))::TEXT, 3, '0') AS payment_number
`

func (q *Queries) GeneratePaymentNumber(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, generatePaymentNumber)
	var payment_number interface{}
	err := row.Scan(&payment_number)
	return payment_number, err
}

const getPaymentByID = `-- name: GetPaymentByID :one

SELECT p.id, p.payment_number, p.customer_id, p.payment_date, p.amount,
       p.deposit_to_account_id, p.journal_entry_id, p.notes,
       p.created_by, p.created_at, p.updated_at,
       c.name AS customer_name,
       a.code AS deposit_account_code, a.name AS deposit_account_name
FROM payments p
JOIN customers c ON c.id = p.customer_id
JOIN accounts a ON a.id = p.deposit_to_account_id
WHERE p.id = $1
`

type GetPaymentByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PaymentNumber      string             `json:"payment_number"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	PaymentDate        pgtype.Date        `json:"payment_date"`
	Amount             pgtype.Numeric     `json:"amount"`
	DepositToAccountID pgtype.UUID        `json:"deposit_to_account_id"`
	JournalEntryID     pgtype.UUID        `json:"journal_entry_id"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CustomerName       string             `json:"customer_name"`
	DepositAccountCode string             `json:"deposit_account_code"`
	DepositAccountName string             `json:"deposit_account_name"`
}

// ============================================================================
// PAYMENTS (Pembayaran)
// ============================================================================
func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (GetPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.CustomerID,
		&i.PaymentDate,
		&i.Amount,
		&i.DepositToAccountID,
		&i.JournalEntryID,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.DepositAccountCode,
		&i.DepositAccountName,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT p.id, p.payment_number, p.customer_id, p.payment_date, p.amount,
       p.deposit_to_account_id, p.journal_entry_id, p.notes,
       p.created_by, p.created_at, p.updated_at,
       c.name AS customer_name,
       a.code AS deposit_account_code, a.name AS deposit_account_name
FROM payments p
JOIN customers c ON c.id = p.customer_id
JOIN accounts a ON a.id = p.deposit_to_account_id
WHERE ($3::UUID IS NULL OR p.customer_id = $3::UUID)
ORDER BY p.payment_date DESC
LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

type ListPaymentsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	PaymentNumber      string             `json:"payment_number"`
	CustomerID         pgtype.UUID        `json:"customer_id"`
	PaymentDate        pgtype.Date        `json:"payment_date"`
	Amount             pgtype.Numeric     `json:"amount"`
	DepositToAccountID pgtype.UUID        `json:"deposit_to_account_id"`
	JournalEntryID     pgtype.UUID        `json:"journal_entry_id"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CustomerName       string             `json:"customer_name"`
	DepositAccountCode string             `json:"deposit_account_code"`
	DepositAccountName string             `json:"deposit_account_name"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Limit, arg.Offset, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsRow
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.CustomerID,
			&i.PaymentDate,
			&i.Amount,
			&i.DepositToAccountID,
			&i.JournalEntryID,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.DepositAccountCode,
			&i.DepositAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
