// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_allocations.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentAllocation = `-- name: CreatePaymentAllocation :one

INSERT INTO payment_allocations (payment_id, invoice_id, amount)
VALUES ($1, $2, $3)
RETURNING id, payment_id, invoice_id, amount, created_at
`

type CreatePaymentAllocationParams struct {
	PaymentID pgtype.UUID    `json:"payment_id"`
	InvoiceID pgtype.UUID    `json:"invoice_id"`
	Amount    pgtype.Numeric `json:"amount"`
}

// ============================================================================
// PAYMENT ALLOCATIONS (Alokasi Pembayaran ke Invoice)
// ============================================================================
func (q *Queries) CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) (PaymentAllocation, error) {
	row := q.db.QueryRow(ctx, createPaymentAllocation, arg.PaymentID, arg.InvoiceID, arg.Amount)
	var i PaymentAllocation
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.InvoiceID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentAllocationsByInvoiceID = `-- name: GetPaymentAllocationsByInvoiceID :many
SELECT pa.id, pa.payment_id, pa.invoice_id, pa.amount, pa.created_at,
       p.payment_number
FROM payment_allocations pa
JOIN payments p ON p.id = pa.payment_id
WHERE pa.invoice_id = $1
ORDER BY pa.created_at ASC
`

type GetPaymentAllocationsByInvoiceIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	PaymentID     pgtype.UUID        `json:"payment_id"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PaymentNumber string             `json:"payment_number"`
}

func (q *Queries) GetPaymentAllocationsByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]GetPaymentAllocationsByInvoiceIDRow, error) {
	rows, err := q.db.Query(ctx, getPaymentAllocationsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentAllocationsByInvoiceIDRow
	for rows.Next() {
		var i GetPaymentAllocationsByInvoiceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.InvoiceID,
			&i.Amount,
			&i.CreatedAt,
			&i.PaymentNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentAllocationsByPaymentID = `-- name: GetPaymentAllocationsByPaymentID :many
SELECT pa.id, pa.payment_id, pa.invoice_id, pa.amount, pa.created_at,
       i.invoice_number
FROM payment_allocations pa
JOIN invoices i ON i.id = pa.invoice_id
WHERE pa.payment_id = $1
ORDER BY pa.created_at ASC
`

type GetPaymentAllocationsByPaymentIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	PaymentID     pgtype.UUID        `json:"payment_id"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	InvoiceNumber string             `json:"invoice_number"`
}

func (q *Queries) GetPaymentAllocationsByPaymentID(ctx context.Context, paymentID pgtype.UUID) ([]GetPaymentAllocationsByPaymentIDRow, error) {
	rows, err := q.db.Query(ctx, getPaymentAllocationsByPaymentID, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentAllocationsByPaymentIDRow
	for rows.Next() {
		var i GetPaymentAllocationsByPaymentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.InvoiceID,
			&i.Amount,
			&i.CreatedAt,
			&i.InvoiceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
